[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2024"

[dependencies]
home = "0.5"
arrayvec = "0.7"
regex = "1"
ndarray = "0.16"
rayon = "1"
thread_local = "1"
once_cell = "1"
num-traits = "0.2"
num-integer = "0.1"
